In [81]:
from scipy.stats import bernoulli,binom,geom,hypergeom,randint,uniform,norm

In [75]:
uniform.rvs(loc=1,scale=9,size=10)

array([2.23588685, 3.16647801, 4.36125434, 9.25792841, 5.67111909,
       6.41748638, 9.74250104, 8.76265592, 7.1427663 , 6.86994136])

In [79]:
uniform.pdf(x=0.4,loc=0,scale=1)

np.float64(1.0)

In [80]:
uniform.cdf(x=0.4,loc=0,scale=1)

np.float64(0.4)

In [83]:
norm.rvs(loc=1.65,scale=0.10,size=100)

array([1.53325047, 1.65310216, 1.69618858, 1.485609  , 1.77742329,
       1.61284191, 1.6408553 , 1.59368447, 1.76191528, 1.65226957,
       1.78251304, 1.74747734, 1.62981813, 1.76939294, 1.5141655 ,
       1.66152578, 1.70817837, 1.61263571, 1.54838035, 1.54551756,
       1.6485248 , 1.76891568, 1.62302592, 1.61081883, 1.6904419 ,
       1.79513713, 1.6010763 , 1.54448926, 1.69369447, 1.60251724,
       1.73872628, 1.71096926, 1.64200057, 1.69387937, 1.64661107,
       1.73671314, 1.61550728, 1.51079034, 1.66149322, 1.61521344,
       1.64854551, 1.65533142, 1.51354401, 1.5757107 , 1.4459496 ,
       1.68616339, 1.81388347, 1.74546986, 1.5524534 , 1.71321538,
       1.56108371, 1.65750637, 1.81992516, 1.52041572, 1.56543556,
       1.66360343, 1.72667013, 1.51513117, 1.64517265, 1.46060331,
       1.53412251, 1.61853848, 1.61763323, 1.65542295, 1.50134108,
       1.69147621, 1.6608335 , 1.64406188, 1.64690347, 1.66359829,
       1.69775018, 1.73066228, 1.79470106, 1.61069837, 1.68716

In [84]:
norm.pdf(x=1.7,loc=1.65,scale=0.10)

np.float64(3.5206532676429947)

In [32]:
bernoulli.rvs(p=2/3,size=100)

array([1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1])

In [33]:
bernoulli.pmf(k=0,p=1/3)

np.float64(0.6666666666666669)

In [34]:
bernoulli.cdf(k=0,p=1/3)

np.float64(0.6666666666666667)

In [35]:
binom.rvs(n=10,p=1/2,size=100)

array([6, 2, 5, 5, 6, 2, 5, 3, 6, 4, 6, 2, 5, 4, 6, 5, 9, 6, 2, 6, 5, 4,
       6, 4, 3, 7, 7, 4, 7, 1, 3, 4, 4, 7, 4, 3, 6, 3, 5, 3, 6, 7, 6, 4,
       4, 5, 6, 6, 7, 4, 5, 4, 8, 5, 8, 4, 5, 3, 6, 4, 8, 5, 8, 5, 6, 4,
       7, 5, 3, 4, 4, 5, 5, 6, 8, 5, 6, 5, 4, 7, 3, 2, 7, 6, 4, 4, 3, 6,
       2, 7, 2, 6, 7, 4, 2, 4, 7, 5, 7, 5])

In [50]:
binom.pmf(k=9,n=10,p=0.5)

np.float64(0.009765625000000003)

In [55]:
geom.rvs(p=1/2,size=100)

array([1, 1, 2, 2, 3, 1, 2, 2, 1, 1, 1, 1, 2, 2, 4, 1, 4, 2, 1, 2, 1, 1,
       2, 7, 1, 1, 5, 1, 2, 1, 1, 2, 3, 1, 1, 2, 2, 2, 1, 4, 3, 2, 2, 1,
       1, 2, 3, 4, 1, 4, 1, 1, 5, 3, 1, 3, 1, 6, 3, 3, 1, 3, 2, 7, 1, 1,
       2, 2, 3, 1, 3, 3, 2, 7, 2, 1, 1, 1, 1, 3, 1, 1, 1, 4, 1, 3, 1, 3,
       1, 2, 2, 2, 2, 1, 1, 1, 1, 4, 2, 1])

In [56]:
geom.pmf(3,0.5)

np.float64(0.125)

In [58]:
geom.cdf(3,0.5)

np.float64(0.875)

In [60]:
hypergeom.rvs(M=20,n=5,N=4,size=100)

array([2, 2, 1, 1, 0, 1, 0, 1, 1, 2, 0, 3, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       2, 1, 1, 0, 2, 2, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 2, 0, 1, 0, 0,
       1, 3, 1, 1, 0, 2, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 2, 2, 2, 1, 2, 1, 1, 2, 0, 1, 3, 2, 1, 0, 2, 0, 2, 2, 1, 1,
       0, 2, 1, 2, 3, 2, 2, 1, 0, 1, 1, 1])

In [71]:
randint.rvs(1,10,size=10)

array([5, 6, 6, 4, 4, 4, 5, 4, 6, 1])

In [73]:
randint.cdf(3,1,11)

np.float64(0.3)